apiVersion: v1
kind: Secret
metadata:
  name: event-hub-secrets
  namespace: event-hub
type: Opaque
stringData:
  MYSQL_PASSWORD: "K6;JSEJ857{E<D=b"
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "jZvgpDf7RbXwFzDo"
  MONGO_URI: "mongodb+srv://root:jZvgpDf7RbXwFzDo@cluster0.du1bfwl.mongodb.net/event-hub-notification-service"
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"

  KEYCLOAK_CLIENT_SECRET: "yJq1nWO8BsEteqCXcDu3CEVZ2quiXus9"
  KEYCLOAK_CONFIG_NAME: "amirumithsara1234@gmail.com"
  KEYCLOAK_CONFIG_PASSWORD: "1234"

  CONFIG_GIT_USERNAME: ""
  CONFIG_GIT_PASSWORD: ""

  AWS_ACCESS_KEY_ID: "AKIAQEIP3PZKXXO3CH4T"
  AWS_SECRET_ACCESS_KEY: "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"

  BREVO_API_KEY: "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"
  BREVO_SENDER_EMAIL: "amirumithsara1234@gmail.com"
  BREVO_SENDER_NAME: "Event Hub"
