apiVersion: v1
kind: Secret
metadata:
  name: event-hub-secrets
  namespace: event-hub
type: Opaque
stringData:
  MYSQL_PASSWORD: "your-db-password"
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "your-mongo-password"
  MONGO_URI: "mongodb+srv://root:your-mongo-password@your-cluster.mongodb.net/event-hub-notification-service"
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"

  KEYCLOAK_CLIENT_SECRET: "your-keycloak-client-secret"
  KEYCLOAK_CONFIG_NAME: "your-user@example.com"
  KEYCLOAK_CONFIG_PASSWORD: "your-keycloak-user-password"

  CONFIG_GIT_USERNAME: ""
  CONFIG_GIT_PASSWORD: ""

  AWS_ACCESS_KEY_ID: "your-aws-access-key"
  AWS_SECRET_ACCESS_KEY: "your-aws-secret-key"

  BREVO_API_KEY: "your-brevo-api-key"
  BREVO_SENDER_EMAIL: "your-sender@example.com"
  BREVO_SENDER_NAME: "Event Hub"
