apiVersion: v1
kind: Secret
metadata:
  name: event-hub-secrets
  namespace: event-hub
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "1234"
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "1234"
  MONGO_URI: "mongodb://root:1234@mongodb:27017/event-hub-notification-service?authSource=admin"
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"

  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "1234"
  KEYCLOAK_CLIENT_SECRET: "yJq1nWO8BsEteqCXcDu3CEVZ2quiXus9"
  KEYCLOAK_CONFIG_PASSWORD: "1234"

  AWS_ACCESS_KEY_ID: "AKIAQEIP3PZKXXO3CH4T"
  AWS_SECRET_ACCESS_KEY: "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"

  BREVO_API_KEY: "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"
  BREVO_SENDER_EMAIL: "amirumithsara1234@gmail.com"
  BREVO_SENDER_NAME: "Event Hub"
