apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
  namespace: event-hub
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS ec7205_event_service;
    CREATE DATABASE IF NOT EXISTS ec7205_booking_service;
    CREATE DATABASE IF NOT EXISTS ec7205_eventHub_auth;
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: event-hub
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: event-hub
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-hub-secrets
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
