apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: event-hub
spec:
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: config-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: event-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: amiru1234/config-server:latest
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: git
            - name: SERVER_PORT
              value: "8888"
            - name: EUREKA_DEFAULT_ZONE
              valueFrom:
                configMapKeyRef:
                  name: event-hub-config
                  key: EUREKA_URL
            - name: CONFIG_GIT_URI
              valueFrom:
                configMapKeyRef:
                  name: event-hub-config
                  key: CONFIG_GIT_URI
            - name: CONFIG_GIT_LABEL
              valueFrom:
                configMapKeyRef:
                  name: event-hub-config
                  key: CONFIG_GIT_LABEL
            - name: CONFIG_GIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: event-hub-secrets
                  key: CONFIG_GIT_USERNAME
            - name: CONFIG_GIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-hub-secrets
                  key: CONFIG_GIT_PASSWORD
