apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: event-hub
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: auth-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: event-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: amiru1234/auth-service-api:latest
          ports:
            - containerPort: 9092
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SERVER_PORT
              value: "9092"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/ec7205_eventHub_auth?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-hub-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: event-hub-config
                  key: EUREKA_URL
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: event-hub-config
                  key: KEYCLOAK_ISSUER_URI
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_TOKEN_URI
              valueFrom:
                configMapKeyRef:
                  name: event-hub-config
                  key: KEYCLOAK_TOKEN_URI
            - name: PUBLIC_KEY_STRING
              valueFrom:
                configMapKeyRef:
                  name: event-hub-config
                  key: PUBLIC_KEY_STRING
            - name: KEYCLOAK_CONFIG_REALM
              valueFrom:
                configMapKeyRef:
                  name: event-hub-config
                  key: KEYCLOAK_REALM
            - name: KEYCLOAK_CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: event-hub-config
                  key: KEYCLOAK_SERVER_URL
            - name: KEYCLOAK_CONFIG_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: event-hub-config
                  key: KEYCLOAK_CLIENT_ID
            - name: KEYCLOAK_CONFIG_GRANT_TYPE
              valueFrom:
                configMapKeyRef:
                  name: event-hub-config
                  key: KEYCLOAK_GRANT_TYPE
            - name: KEYCLOAK_CONFIG_NAME
              valueFrom:
                configMapKeyRef:
                  name: event-hub-config
                  key: KEYCLOAK_CONFIG_NAME
            - name: KEYCLOAK_CONFIG_SECRET
              valueFrom:
                secretKeyRef:
                  name: event-hub-secrets
                  key: KEYCLOAK_CLIENT_SECRET
            - name: KEYCLOAK_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-hub-secrets
                  key: KEYCLOAK_CONFIG_PASSWORD
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: event-hub-secrets
                  key: RABBITMQ_DEFAULT_USER
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-hub-secrets
                  key: RABBITMQ_DEFAULT_PASS
            - name: EVENTHUB_NOTIFICATION_AUTH_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: event-hub-config
                  key: AUTH_NOTIFICATION_QUEUE
            - name: ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: event-hub-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: event-hub-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: BUCKETNAME
              valueFrom:
                configMapKeyRef:
                  name: event-hub-config
                  key: AWS_BUCKET_NAME
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: event-hub-config
                  key: AWS_REGION
