apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: event-hub
spec:
  ports:
    - port: 9091
      targetPort: 9091
  selector:
    app: event-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  namespace: event-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
        - name: event-service
          image: amiru1234/event-service-api:latest
          ports:
            - containerPort: 9091
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SERVER_PORT
              value: "9091"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/ec7205_event_service?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-hub-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: event-hub-config
                  key: EUREKA_URL
            - name: JWT_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: event-hub-config
                  key: KEYCLOAK_ISSUER_URI
            - name: ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: event-hub-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: event-hub-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: BUCKETNAME
              valueFrom:
                configMapKeyRef:
                  name: event-hub-config
                  key: AWS_BUCKET_NAME
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: event-hub-config
                  key: AWS_REGION
