apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: event-hub
spec:
  ports:
    - port: 9094
      targetPort: 9094
  selector:
    app: notification-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: event-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: amiru1234/notification-service-api:latest
          ports:
            - containerPort: 9094
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "9094"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: event-hub-secrets
                  key: MONGO_URI
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: event-hub-secrets
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-hub-secrets
                  key: RABBITMQ_DEFAULT_PASS
            - name: AUTH_NOTIFICATION_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: event-hub-config
                  key: AUTH_NOTIFICATION_QUEUE
            - name: BOOKING_NOTIFICATION_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: event-hub-config
                  key: BOOKING_NOTIFICATION_QUEUE
            - name: BREVO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: event-hub-secrets
                  key: BREVO_API_KEY
            - name: BREVO_SENDER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: event-hub-secrets
                  key: BREVO_SENDER_EMAIL
            - name: BREVO_SENDER_NAME
              valueFrom:
                secretKeyRef:
                  name: event-hub-secrets
                  key: BREVO_SENDER_NAME
