apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: event-hub-ingress
  namespace: event-hub
spec:
  ingressClassName: nginx
  rules:
    - host: api.eventhub.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 9090
    - host: app.eventhub.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-ticket
                port:
                  number: 3000
    - host: admin.eventhub.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-admin
                port:
                  number: 4000
    - host: keycloak.eventhub.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
